version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    entrypoint: "tail -f /dev/null"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - "5432:5432"